wandb_version: 1

architecture:
  desc: null
  value: nnUNet
dataset:
  desc: null
  value: AMOS2022
epochs:
  desc: null
  value: 1000
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719902721
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.10.14
      5: 0.17.3
      8:
      - 5
      13: linux-x86_64
